// Embedded DejaVu Sans subset (Latin + Hebrew) for LVGL Tiny-TTF.
// Generated by scripts/gen_font.py (`just gen-font`).
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t  font_dejavu_heb_ttf[];
extern const size_t   font_dejavu_heb_ttf_len;
