#!/usr/bin/env python3
"""Subset DejaVu Sans to Latin + Hebrew and emit it as a C byte array.

LVGL's Tiny-TTF decoder renders a real TTF at runtime, so we only need a small
subsetted font embedded in flash (one file covers every size we ask for). The
default Montserrat font is Latin-only, which is why Hebrew song titles render as
tofu boxes; DejaVu Sans includes the Hebrew block (U+0590..U+05FF).

Run via `just gen-font` (uses the uv venv). Regenerate only when the glyph
coverage changes; the output C file is committed.
"""
import sys
from pathlib import Path
from fontTools import subset

SRC = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
OUT_C = Path("components/ui/fonts/font_dejavu_heb.c")
SYM = "font_dejavu_heb_ttf"

# Glyph coverage: ASCII, Latin-1 + Latin Extended-A (accented European names),
# and the full Hebrew block (letters + niqqud + punctuation).
UNICODES = [
    (0x0020, 0x007F),
    (0x00A0, 0x017F),
    (0x0590, 0x05FF),
    (0x200E, 0x200F),  # LRM / RLM bidi marks
]


def subset_ttf(src: str) -> bytes:
    unicodes = []
    for lo, hi in UNICODES:
        unicodes.extend(range(lo, hi + 1))
    opts = subset.Options()
    opts.flavor = None          # plain TTF (Tiny-TTF wants raw glyf, not woff2)
    opts.desubroutinize = True
    opts.recalc_bounds = True
    opts.drop_tables += ["GSUB", "GPOS"]  # no shaping needed for Hebrew/Latin
    font = subset.load_font(src, opts)
    subsetter = subset.Subsetter(options=opts)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    import io
    buf = io.BytesIO()
    subset.save_font(font, buf, opts)
    return buf.getvalue()


def emit_c(data: bytes, out: Path, sym: str):
    lines = [
        "// Generated by scripts/gen_font.py — DejaVu Sans subset (Latin + Hebrew).",
        "// Embedded TTF for LVGL Tiny-TTF; do not edit by hand.",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"const uint8_t {sym}[] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"const size_t {sym}_len = sizeof({sym});")
    lines.append("")
    out.write_text("\n".join(lines))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else SRC
    if not Path(src).exists():
        sys.exit(f"font not found: {src}")
    data = subset_ttf(src)
    OUT_C.parent.mkdir(parents=True, exist_ok=True)
    emit_c(data, OUT_C, SYM)
    print(f"wrote {OUT_C} ({len(data)} bytes TTF -> {OUT_C.stat().st_size} bytes C)")


if __name__ == "__main__":
    main()
